//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialEyesForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int Id { get; set; }
        public int IdTipoArea { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaMapa { get; set; }
        public System.Data.Entity.Spatial.DbGeography Area1 { get; set; }
    
        public virtual TipoArea TipoArea { get; set; }
    }
}
