//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialEyesForest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeoContext : DbContext
    {
        public GeoContext()
            : base("name=GeoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<Motivo> Motivos { get; set; }
        public virtual DbSet<TipoArea> TipoAreas { get; set; }
        public virtual DbSet<TipoEvento> TipoEventos { get; set; }
    }
}
