USE sitconsu_foresteye
GO

--
/*
DROP TABLE Media
DROP TABLE Area;
DROP TABLE Evento;
DROP TABLE TipoEvento;
DROP TABLE Motivo;
DROP TABLE TipoArea;
GO
--*/

CREATE TABLE TipoEvento (
Id INT IDENTITY NOT NULL,
Nombre VARCHAR(255) NOT NULL,
CONSTRAINT pk_TipoEvento PRIMARY KEY CLUSTERED (Id ASC)
);
GO

CREATE TABLE Motivo (
Id INT IDENTITY NOT NULL,
Nombre VARCHAR(255) NOT NULL,
CONSTRAINT pk_Motivo PRIMARY KEY CLUSTERED (Id ASC)
);
GO

CREATE TABLE TipoArea (
Id INT IDENTITY NOT NULL,
Nombre VARCHAR(255) NOT NULL,
CONSTRAINT pk_TipoArea PRIMARY KEY CLUSTERED (Id ASC)
);
GO

--DROP TABLE Evento
CREATE TABLE Evento (
Id INT IDENTITY (1, 1) NOT NULL,
--IdUsuario INT NOT NULL,
FechaEvento DATETIME NOT NULL,
Localizacion GEOGRAPHY NOT NULL,
Ubicacion VARCHAR(255) NOT NULL,
IdTipoEvento INT NOT NULL, --Idtabla = 1
IdMotivo INT NOT NULL, --IdTabla = 2
SubMotivo VARCHAR(255) NULL,
Observaciones VARCHAR(MAX) NULL,
--Version INT,
CONSTRAINT pk_Evento PRIMARY KEY CLUSTERED (Id ASC)
);
GO

SELECT *,Localizacion.ToString() FROM Evento
SELECT * FROM Media

ALTER TABLE Evento 
ADD CONSTRAINT FK_Evento_TipoEvento
FOREIGN KEY (IdTipoEvento)
REFERENCES TipoEvento (Id);
GO
ALTER TABLE Evento 
ADD CONSTRAINT FK_Evento_Motivo
FOREIGN KEY (IdMotivo)
REFERENCES Motivo (Id);
GO

CREATE TABLE Media (
Id INT IDENTITY(1, 1) NOT NULL,
IdEvento INT NOT NULL,
NombreArchivo VARCHAR(255) NOT NULL,
TipoMedia TINYINT NOT NULL,
CONSTRAINT pk_Media PRIMARY KEY CLUSTERED (Id ASC)
);
GO
ALTER TABLE Media
ADD CONSTRAINT FK_Media_Evento
FOREIGN KEY (IdEvento)
REFERENCES Evento (Id);
GO

CREATE TABLE Area (
Id INT IDENTITY NOT NULL,
IdTipoArea INT NOT NULL,
FechaModificacion DATETIME NOT NULL,
FechaMapa SMALLDATETIME NULL,
--IdUsuario INT NOT NULL,
Area GEOGRAPHY NOT NULL,
CONSTRAINT pk_Area PRIMARY KEY CLUSTERED (Id ASC)
);
GO

ALTER TABLE Area 
ADD CONSTRAINT FK_Area_TipoArea
FOREIGN KEY (IdTipoArea)
REFERENCES TipoArea (Id);
GO

